### ISSUE TITLE
Please restore my copyright notice

### ISSUE THREAD

**Issue by randombit** [NilFoundation/crypto3-rust#1]
This code is derived from https://github.com/randombit/botan-rs

In 892c79623f2e14b386f02 you subsequently removed my copyright notice. This is not allowed by the MIT license which clearly states as a condition "The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software."

**Comment by nemo1369** [comment]
@randombit My bad. This might be an auto-refactoring issue. Restored. And thank you for a bindings library.
